Fixing bvezsenyi.c
As seen in Travis build master Merge pull request #41 from agosdahu/bvezsenyi_refactor_my_l
Bvezsenyi refactor my led blinky

 Commit e0a39df 
 Compare 7f4f286..e0a39df 
 Branch master 
  avatar agosdahu

 #10 failed

ledProject/bvezsenyi_func.c: In function ‘state_func’:
ledProject/bvezsenyi_func.c:69:5: error: too many arguments to function ‘bvezsenyi_led_handler’
     bvezsenyi_led_handler( actual_state_container_p );

In file included from ledProject/bvezsenyi_func.c:1:0:
ledProject/bvezsenyi_func.h:24:6: note: declared here
 void bvezsenyi_led_handler( void );
      ^
make: *** [ledProject/bvezsenyi_func.o] Error 1